[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
match = "(main|master)"
prerelease_token = "rc"
prerelease = false
version_variables = ["setup.py:__version__"]
commit_parser = "emoji"