name: pytest 3.11

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/pytest.yml
    with:
      python-version: "3.11"
